git:
  depth: 3

language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6

env:
  - DB=sqlite

matrix:
  fast_finish: true

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.x ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv config-add tests/php.ini
  - composer install

script:
  - vendor/bin/phinx --configuration=phinx.yml migrate -e $DB
  - vendor/bin/phinx --configuration=phinx.yml seed:run -e $DB
  - phpunit -c tests/units.$DB.xml
  - phpunit tests/configtest
