git:
  depth: 3

language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6

services:
  - postgresql

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.x ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv config-add tests/php.ini
  - composer install

script:
  - psql -c 'create database jitamin_unit_test;' -U postgres
  - vendor/bin/phinx --configuration=phinx.yml migrate -e travis
  - vendor/bin/phinx --configuration=phinx.yml seed:run -e travis
  - phpunit -c tests/units.postgres.xml
  - phpunit tests/configtest
